### ISSUE TITLE
Subpackage shadows default package name

### ISSUE THREAD

**Issue by kitemongerer** [cloudfoundry-incubator/go-log-cache#9]
The import `code.cloudfoundry.org/go-log-cache`, resolves to logcache
The import of the sub package `code.cloudfoundry.org/go-log-cache/rpc/logcache` also resolves to logcache

We are importing the sub package to access envelope type constants while building ReadOptions.

It would be nice if these names didn't collide or if the constants were exported at a higher level.

**Comment by apoydence** [comment]
@kitemongerer We have felt this pain a little but mitigated it by always renaming the `code.cloudfoundry.org/go-log-cache/rpc/logcache` to `rpc`.

The other pattern we have done on Loggregator is `loggregator_v2` for the generated code. This would translate to `logcache_v1` for log cache. I'm interested in what other team members think?

I see 2 options:
1. Leave it and continue to have users rename to `rpc`
2. Adopt Loggregator's pattern and update the package name to `logcache_v1` (breaking change, but we're not GA yet...)

Thoughts?

**Comment by kitemongerer** [comment]
Why don't you want to just move everything from the `rpc/logcache` package into just `rpc` since the logcache package is the only thing in rpc?

**Comment by apoydence** [comment]
@kitemongerer This is generated code. I think it would be wrong to update the protocol buffer files to have a package of "rpc". I would prefer to follow the pattern that loggregator has.

**Comment by apoydence** [comment]
We elected to rename the package to `logcache_v1`.
